name: Awesome README
author: Marcelo Trylesinski <marcelotryle@gmail.com>
description: Populate an Awesome README given repositories data

inputs:
  template_path:
    description: README template path.
    default: README.md.jinja
    required: false

  data_path:
    description: YAML path containing repositories data.
    default: awesome.yaml
    required: false

  output_path:
    description: README output path.
    default: README.md
    required: false

runs:
  using: composite
  steps:
    - name: Install requirements
      run: python -m pip install -r requirements.txt
      shell: bash

    - name: Load environment
      run: |
        echo "template_path=${{inputs.template_path}}" >> $GITHUB_ENV
        echo "data_path=${{inputs.data_path}}" >> $GITHUB_ENV
        echo "output_path=${{inputs.output_path}}" >> $GITHUB_ENV
      shell: bash

    - name: Render README
      run: python ${{ github.action_path }}/main.py
      shell: bash

    - name: Commit README
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git status
        git add .
        git commit -am "📝 Update README"
        git push
      shell: bash
