name: Render README

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/actions"
      - "awesome.yaml"
  schedule:
    - cron: "0 0 * * FRI"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Render README
        uses: ./.github/actions/awesome
