name: Render README

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/actions"
      - "awesome.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/actions"
      - "awesome.yaml"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * FRI"

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Render README
        uses: ./.github/actions/awesome
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
