name: Render README

on:
  push:
    branches:
      - "main"
    paths:
      - "awesome.yaml"

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Render README
        uses: ./.github/actions/awesome
